# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RemoteDesktop(object):
    def setupUi(self, RemoteDesktop):
        RemoteDesktop.setObjectName("RemoteDesktop")
        RemoteDesktop.resize(1009, 632)
        RemoteDesktop.setStyleSheet("background-color: rgb(245, 247, 250)")
        self.centralwidget = QtWidgets.QWidget(parent=RemoteDesktop)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 95, 469, 470))
        self.widget.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(230, 233, 237);\n"
"border-radius: 10px;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(20, 30, 401, 38))
        font = QtGui.QFont()
        font.setFamily("Inter Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 0px;\n"
"font: 25 18pt \"Inter Light\";\n"
"color: rgb(0, 0, 0);")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label.setLineWidth(0)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(34, 93, 138, 37))
        self.label_2.setStyleSheet("border: 0px;\n"
"font: 25 13pt \"Inter Light\";\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(34, 189, 116, 31))
        self.label_3.setStyleSheet("border: 0px;\n"
"font: 25 13pt \"Inter Light\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.my_pass = QtWidgets.QLineEdit(parent=self.widget)
        self.my_pass.setGeometry(QtCore.QRect(34, 230, 309, 39))
        self.my_pass.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;\n"
"font: 12 12pt \"Inter ExtraLight\";")
        self.my_pass.setObjectName("my_pass")
        self.your_ip = QtWidgets.QLabel(parent=self.widget)
        self.your_ip.setGeometry(QtCore.QRect(34, 140, 309, 39))
        self.your_ip.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"border-radius: 0px;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12 12pt \"Inter ExtraLight\";")
        self.your_ip.setObjectName("your_ip")
        self.audio = QtWidgets.QRadioButton(parent=self.widget)
        self.audio.setGeometry(QtCore.QRect(34, 290, 311, 41))
        self.audio.setStyleSheet("border: 0px;\n"
"font: 25 12pt \"Inter Light\";\n"
"color: rgb(0, 0, 0);")
        self.audio.setObjectName("audio")
        self.open_connect = QtWidgets.QPushButton(parent=self.widget)
        self.open_connect.setGeometry(QtCore.QRect(34, 380, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Inter ExtraBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.open_connect.setFont(font)
        self.open_connect.setStyleSheet("QPushButton {\n"
"    background-color: rgb(71, 112, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 81 16pt \"Inter ExtraBold\";\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(82, 144, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 81 16pt \"Inter ExtraBold\";\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}")
        self.open_connect.setObjectName("open_connect")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(5, 5, 281, 38))
        font = QtGui.QFont()
        font.setFamily("Inter Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border: 0px;\n"
"font: 25 18pt \"Inter Light\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_9.setLineWidth(0)
        self.label_9.setObjectName("label_9")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(510, 95, 469, 470))
        self.widget_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(230, 233, 237);\n"
"border-radius: 10px;")
        self.widget_2.setObjectName("widget_2")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 431, 38))
        font = QtGui.QFont()
        font.setFamily("Inter Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 0px;\n"
"font: 25 18pt \"Inter Light\";\n"
"color: rgb(0, 0, 0);")
        self.label_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_5.setLineWidth(0)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(34, 93, 138, 37))
        self.label_6.setStyleSheet("border: 0px;\n"
"font: 25 13pt \"Inter Light\";\n"
"color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(34, 189, 116, 31))
        self.label_7.setStyleSheet("border: 0px;\n"
"font: 25 13pt \"Inter Light\";\n"
"color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.record = QtWidgets.QRadioButton(parent=self.widget_2)
        self.record.setGeometry(QtCore.QRect(34, 290, 311, 41))
        self.record.setStyleSheet("border: 0px;\n"
"font: 25 12pt \"Inter Light\";\n"
"color: rgb(0, 0, 0);")
        self.record.setObjectName("record")
        self.connect = QtWidgets.QPushButton(parent=self.widget_2)
        self.connect.setGeometry(QtCore.QRect(34, 380, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Inter ExtraBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.connect.setFont(font)
        self.connect.setStyleSheet("QPushButton {\n"
"    background-color: rgb(71, 112, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 81 16pt \"Inter ExtraBold\";\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(82, 144, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 81 16pt \"Inter ExtraBold\";\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}")
        self.connect.setObjectName("connect")
        self.server_ip = QtWidgets.QLineEdit(parent=self.widget_2)
        self.server_ip.setGeometry(QtCore.QRect(34, 140, 309, 39))
        self.server_ip.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;\n"
"font: 12 12pt \"Inter ExtraLight\";")
        self.server_ip.setObjectName("server_ip")
        self.pass_server = QtWidgets.QLineEdit(parent=self.widget_2)
        self.pass_server.setGeometry(QtCore.QRect(34, 230, 309, 39))
        self.pass_server.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;\n"
"font: 12 12pt \"Inter ExtraLight\";")
        self.pass_server.setObjectName("pass_server")
        RemoteDesktop.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=RemoteDesktop)
        self.statusbar.setObjectName("statusbar")
        RemoteDesktop.setStatusBar(self.statusbar)

        self.retranslateUi(RemoteDesktop)
        QtCore.QMetaObject.connectSlotsByName(RemoteDesktop)
        self.op_click = False
        self.con_click = False
        self.open_connect.clicked.connect(self.open_click)
        self.connect.clicked.connect(self.connect_click)
        
    def open_click(self):
        if not self.op_click:
            self.open_connect.setText("Close Connect")
        else:
            self.open_connect.setText("Open Connect")
        self.op_click = not self.op_click
        
    def connect_click(self):
        if not self.con_click:
            self.connect.setText("Close Connect")
        else:
            self.connect.setText("Connect")
        self.con_click = not self.con_click

    def retranslateUi(self, RemoteDesktop):
        _translate = QtCore.QCoreApplication.translate
        RemoteDesktop.setWindowTitle(_translate("RemoteDesktop", "Remote Desktop"))
        self.label.setText(_translate("RemoteDesktop", "ALLOW REMOTE CONTROL"))
        self.label_2.setText(_translate("RemoteDesktop", "Your IP"))
        self.label_3.setText(_translate("RemoteDesktop", "Password"))
        self.my_pass.setPlaceholderText(_translate("RemoteDesktop", "Enter Password"))
        self.your_ip.setText(_translate("RemoteDesktop", "192.168.0.12"))
        self.audio.setText(_translate("RemoteDesktop", "Allow share computer audio"))
        self.open_connect.setText(_translate("RemoteDesktop", "Open Connect"))
        self.label_9.setText(_translate("RemoteDesktop", "REMOTE DESKTOP"))
        self.label_5.setText(_translate("RemoteDesktop", "CONTROL REMOTE DESKTOP"))
        self.label_6.setText(_translate("RemoteDesktop", "Server IP"))
        self.label_7.setText(_translate("RemoteDesktop", "Password"))
        self.record.setText(_translate("RemoteDesktop", "Record remote control"))
        self.connect.setText(_translate("RemoteDesktop", "Connect"))
        self.server_ip.setPlaceholderText(_translate("RemoteDesktop", "Enter IP"))
        self.pass_server.setPlaceholderText(_translate("RemoteDesktop", "Enter Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemoteDesktop = QtWidgets.QMainWindow()
    ui = Ui_RemoteDesktop()
    ui.setupUi(RemoteDesktop)
    RemoteDesktop.show()
    sys.exit(app.exec())
